name: Java Gradle CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build Java application
    runs-on: self-hosted

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '25'
          cache: gradle

      - name: Check Java version
        run: java -version

      - name: Check Gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog
        run: |
          jf config remove jfrog-server --quiet || true

          jf config add jfrog-server \
            --url="${{ vars.JF_URL }}" \
            --access-token="${{ secrets.JF_ACCESS_TOKEN }}" \
            --interactive=false

      - name: Upload JAR to JFrog
        run: |
          jf rt upload \
            "build/libs/*.jar" \
            "java-app-local/java-gradle-demo/${{ github.run_number }}/"


  dev-deploy:
    name: Deploy to Development
    needs: build
    environment:
      name: dev
    runs-on: self-hosted

    steps:

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog
        run: |
          jf config remove jfrog-server --quiet || true

          jf config add jfrog-server \
            --url="${{ vars.JF_URL }}" \
            --access-token="${{ secrets.JF_ACCESS_TOKEN }}" \
            --interactive=false

      - name: Download JAR from JFrog
        run: |
          jf rt download \
            "java-app-local/java-gradle-demo/${{ github.run_number }}/*.jar" \
            .
      - name: Check downloaded files
        run: |
           pwd
           ls -lah
           find -maxdepth 2 -type f -name "*.jar" -print
      - name: Deploy to Dev
        run: |
          cp *.jar /opt/devops-demo/dev/
          ls -lh /opt/devops-demo/dev/
