name: Java Gradle CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build Java application
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '25'
          cache: gradle

      - name: Check Java version
        run: java -version

      - name: Check Gradle version
        run: gradle --version

      - name: Build with Gradle
        run: gradle clean build

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure JFrog
        run: |
          jf config add jfrog-server \
            --url="${{ vars.JF_URL }}" \
            --access-token="${{ secrets.JF_ACCESS_TOKEN }}" \
            --interactive=false

      - name: Upload JAR to JFrog
        run: |
          jf rt upload \
            "build/libs/*.jar" \
            "java-app-local/java-gradle-demo/${{ github.run_number }}/"
 


     # - name: Upload JAR artifact
     #   uses: actions/upload-artifact@v4
     #   with:
      #    name: java-application
      #    path: build/libs/*.jar

      #Below step is deploying .jar file directly from 
      # github runner group to ec2 instance

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
            ls -l ec2_key.pem
            wc -c ec2_key.pem
            chmod 600 ec2_key.pem

          scp -o StrictHostKeyChecking=no \
            -i ec2_key.pem \
            build/libs/*.jar \
            ec2-user@${{ secrets.EC2_HOST }}:/opt/devops-demo/

          ssh -o StrictHostKeyChecking=no \
            -i ec2_key.pem \
            ec2-user@${{ secrets.EC2_HOST }} \
            "ls -lh /opt/devops-demo/"

          rm -f ec2_key.pem
